[package]
name = "loggers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.21"
syn = {version = "1.0.103", features = ["full"]}

[lib]
proc-macro = true