// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CFSide } from "./CFSide";

export interface ConflictLine { text: string, side: CFSide, section: number, key: string, }