// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WipPatchType } from "./WipPatchType";

export interface WipPatch { oldFile: string, newFile: string, patchType: WipPatchType, stagedType: WipPatchType, unStagedType: WipPatchType, conflicted: boolean, id: string, isImage: boolean, }