// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WipPatch } from "./WipPatch";

export interface WipPatches { patches: Array<WipPatch>, conflict_commit_id: string | null, }