// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionError } from "./ActionError";

export type ActionState = { stdout: Array<string>, stderr: Array<string>, done: boolean, error: ActionError | null, };