// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlankLine } from "./BlankLine";
import type { ConflictLine } from "./ConflictLine";
import type { OkLine } from "./OkLine";
import type { SlotLine } from "./SlotLine";

export type CFLine =
  | { ok: OkLine }
  | { blank: BlankLine }
  | { slot: SlotLine }
  | { conflict: ConflictLine };
