// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OkLine } from "./OkLine";
import type { SlotLine } from "./SlotLine";

export type CFLine = { "ok": OkLine } | { "slot": SlotLine };
