// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BlankLine } from "./BlankLine";
import type { ConflictLine } from "./ConflictLine";

export type CFSectionLine = { "blank": BlankLine } | { "conflict": ConflictLine };
