// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CodeSearchOpts = { repoPath: string, searchText: string, numResults: number, startCommitIndex: number, };
