// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CFSection } from "./CFSection";
import type { ConflictedFileLine } from "./ConflictedFileLine";

export interface ConflictedFile {
  lines: Array<ConflictedFileLine>;
  sections: Array<CFSection>;
  refNameTop: string;
  refNameBottom: string;
  lineEnding: string;
  maxLineLength: number;
}
