// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictedSide } from "./ConflictedSide";

export interface ConflictedLine {
  text: string;
  blank: boolean;
  side: ConflictedSide;
  section: number;
  conflicted: boolean;
  key: string | null;
}
