// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictedLine } from "./ConflictedLine";

export interface ConflictedSection {
  left: Array<ConflictedLine>;
  right: Array<ConflictedLine>;
}
