// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictedFileLine } from "./ConflictedFileLine";
import type { ConflictedSection } from "./ConflictedSection";

export interface ConflictedFile {
  lines: Array<ConflictedFileLine>;
  sections: Array<ConflictedSection>;
  refNameTop: string;
  refNameBottom: string;
  lineEnding: string;
  maxLineLength: number;
}
