// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CFLine } from "./CFLine";
import type { CFSection } from "./CFSection";

export type ConflictedFile = { lines: Array<CFLine>, sections: Array<CFSection>, refNameTop: string, refNameBottom: string, lineEnding: string, maxLineLength: number, };
