// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HunkLine } from "./HunkLine";
import type { Patch } from "./Patch";
import type { SearchMatchType } from "./SearchMatchType";

export interface CoreSearchResult {
  commitId: string;
  matches: Array<SearchMatchType>;
  patches: Array<Patch>;
  diffs: Record<string, Array<HunkLine>>;
}
