// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileMatch } from "./FileMatch";
import type { Patch } from "./Patch";
import type { SearchMatchType } from "./SearchMatchType";

export type CoreSearchResult = { commitId: string, matches: Array<SearchMatchType>, patches: Array<Patch>, diffs: Array<FileMatch>, refIds: Array<string>, };
