// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HunkLine } from "./HunkLine";
import type { Patch } from "./Patch";

export interface FileMatch {
  patch: Patch;
  lines: Array<HunkLine>;
}
