// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitConfig = { entries: { [key in string]?: string }, remotes: { [key in string]?: string }, submodules: { [key in string]?: string }, };
