// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitConfig = { entries: { [key: string]: string }, remotes: { [key: string]: string }, submodules: { [key: string]: string }, };
