// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Commit } from "./Commit";
import type { RefInfo } from "./RefInfo";

export interface HeadInfo {
  ref: RefInfo;
  commit: Commit;
  remoteRef: RefInfo | null;
  remoteCommit: Commit | null;
  remoteAhead: number;
  remoteBehind: number;
}
