// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HunkLine } from "./HunkLine";
import type { HunkRange } from "./HunkRange";

export interface Hunk {
  oldLineRange: HunkRange;
  newLineRange: HunkRange;
  contextLine: string;
  lines: Array<HunkLine>;
  index: number;
}
