// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LineInstruction } from "./LineInstruction";
import type { PointInstruction } from "./PointInstruction";

export interface Instructions {
  points: Array<PointInstruction>;
  lines: Array<LineInstruction>;
}
