// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitPoint } from "./CommitPoint";

export interface LineInstruction {
  points: Array<CommitPoint>;
  colour: string;
  id: string;
}
