// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LocalRefCommitDiff = { aheadOfRemote: number, behindRemote: number, aheadOfHead: number, behindHead: number, };