// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ACType } from "./ACType";

export interface MessageAC {
  currentWord: string;
  repoPath: string;
  maxNum: number;
  kind: ACType;
}
