// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PatchType } from "./PatchType";

export type Patch = { commitId: string, oldFile: string, newFile: string, patchType: PatchType, id: string, isImage: boolean, };
