// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PointInstruction {
  x: number;
  y: number;
  colour: string;
  isMerge: boolean;
  commitId: string;
}
