// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitFilter } from "./CommitFilter";

export type ReqCommitsOptions2 = { repoPath: string, numCommits: number, filters: Array<CommitFilter>, fast: boolean, skipStashes: boolean, };