// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitConfig } from "./GitConfig";
import type { HeadInfo } from "./HeadInfo";
import type { WipPatches } from "./WipPatches";

export interface WsRepoState {
  patches: WipPatches;
  config: GitConfig;
  headInfo: HeadInfo;
}
